### ISSUE TITLE
fix_telecined_fades returns green clip

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deinterlace#15]
This function, for me, always returns a green clip.

```py
    tivtc = tivtc_2pass(clip, 1, tfm_args=dict(order=1, slow=2, mChroma=False))

    return tivtc, depth(fix_telecined_fades(depth(tivtc, 32)), 16).std.SetFieldBased(0)
```

![image](https://user-images.githubusercontent.com/42927908/208596285-d0c11dbb-ff0f-4a4b-a13b-ce1535857be9.png)
![image](https://user-images.githubusercontent.com/42927908/208596326-e54b8acf-e0fe-4a7c-bc5a-1a0918cfa6a0.png)

This also happens at 8bit and 16bit.

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-deinterlace/commit/96c32a8c85d2b6f80b79ee9fd9d983bb723b145f
