### ISSUE TITLE
tivtc_vfr: Function not releasing IVTC'd clip

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deinterlace#9]
*Moved from [this issue](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/issues/140)*.

The function currently has a tendency to refuse to release the ivtc'd clip and the relevant files, causing an error and forcing users to refresh their previewer.

_Originally posted by @Setsugennoao in https://github.com/Irrational-Encoding-Wizardry/lvsfunc/pull/139#discussion_r906648786_

**Comment by Setsugennoao** [comment]
Fixed in 6e80d2ddc9146dff0a89281704059e7782d62828
